version: '3.8'

services:
  test:
    image: python:3.10-slim
    container_name: mrjbot_simple_test
    volumes:
      - ./test_components_simple.py:/app/test_components_simple.py
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir psycopg2-binary redis &&
             python test_components_simple.py"
    networks:
      - mrjbot_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:15-alpine
    container_name: test_simple_postgres
    environment:
      POSTGRES_DB: mrjbot
      POSTGRES_USER: mrjbot
      POSTGRES_PASSWORD: mrjbot
    volumes:
      - postgres_simple_test_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrjbot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mrjbot_network

  redis:
    image: redis:7-alpine
    container_name: test_simple_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_simple_test_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mrjbot_network

volumes:
  postgres_simple_test_data:
  redis_simple_test_data:

networks:
  mrjbot_network:
    driver: bridge 