services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/threexui
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ALGORITHM=HS256
      - BACKEND_CORS_ORIGINS=["http://localhost:3000"]
      - ENVIRONMENT=development
      - SERVER_IP=localhost
      - USE_SSL=false
      - ENABLE_BOT=false
      - ENABLE_FRONTEND=true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    depends_on:
      - backend
    volumes:
      - ./bot:/app/bot
    environment:
      - BACKEND_API_URL=http://backend:8000/api
      - BOT_TOKEN=your-telegram-bot-token
      - ENABLE_BOT=false

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: threexui
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
  redis_data: 