FROM node:18-alpine

# Set environment variables
ENV NODE_ENV=production
ENV GENERATE_SOURCEMAP=false

# Set work directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies with specific flags for production
RUN npm ci --only=production --legacy-peer-deps

# Copy project files
COPY frontend .

# Build the app
RUN npm run build

# Install serve
RUN npm install -g serve

# Start the app
CMD ["serve", "-s", "build", "-l", "3000"] 