from setuptools import setup, find_packages

setup(
    name="mrjbot",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "click>=8.0.0",
        "sqlalchemy>=2.0.0",
        "asyncpg>=0.27.0",
        "python-telegram-bot>=20.0",
        "redis>=4.5.0",
        "aiohttp>=3.8.0",
        "python-dotenv>=0.19.0",
        "pydantic>=2.0.0",
        "alembic>=1.9.0",
        "psycopg2-binary>=2.9.0",
        "cryptography>=41.0.0",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "bcrypt>=4.0.0",
        "uvicorn>=0.23.0",
        "fastapi>=0.100.0",
        "python-multipart>=0.0.6",
        "aiofiles>=23.1.0",
        "jinja2>=3.1.0",
        "aioredis>=2.0.0",
        "tenacity>=8.2.0",
        "structlog>=23.1.0",
        "prometheus-client>=0.17.0",
        "sentry-sdk>=1.30.0",
        "pytest>=7.3.1",
        "pytest-asyncio>=0.21.0",
        "pytest-cov>=4.1.0",
        "black>=23.3.0",
        "isort>=5.12.0",
        "flake8>=6.0.0",
        "mypy>=1.3.0",
    ],
    entry_points={
        "console_scripts": [
            "mrjbot=bot.cli.main:cli",
        ],
    },
    author="MRJ",
    author_email="mrj@example.com",
    description="A powerful V2Ray management bot with multi-server support",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mrj/mrjbot",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.8",
) 