version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: test_db
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - django_network

  web:
    image: python:3.10-slim
    container_name: test_web
    command: >
      sh -c "pip install django psycopg2-binary &&
             django-admin startproject mysite . &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge 