# Generated by Django 5.0.2 on 2025-03-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='ID of the client in 3x-UI', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('enable', models.BooleanField(default=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('total', models.BigIntegerField(default=0, help_text='Total traffic limit in bytes (0 means unlimited)')),
                ('up', models.BigIntegerField(default=0, help_text='Upload traffic in bytes')),
                ('down', models.BigIntegerField(default=0, help_text='Download traffic in bytes')),
                ('settings', models.JSONField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmess_link', models.TextField(blank=True, null=True)),
                ('vless_link', models.TextField(blank=True, null=True)),
                ('trojan_link', models.TextField(blank=True, null=True)),
                ('shadowsocks_link', models.TextField(blank=True, null=True)),
                ('subscription_url', models.URLField(blank=True, null=True)),
                ('qrcode_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='v2ray.client')),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_id', models.PositiveIntegerField(help_text='ID of the inbound in 3x-UI')),
                ('protocol', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('network', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('listen', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.BigIntegerField(default=0, help_text='Total traffic limit in bytes (0 means unlimited)')),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('up', models.BigIntegerField(default=0, help_text='Upload traffic in bytes')),
                ('down', models.BigIntegerField(default=0, help_text='Download traffic in bytes')),
                ('settings', models.JSONField(blank=True, null=True)),
                ('stream_settings', models.JSONField(blank=True, null=True)),
                ('sniffing', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='main.server')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='v2ray.inbound'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='main.server')),
            ],
        ),
    ]
